#!/bin/bash
#script that creates 2 random numbers, their square roots and the sum of their square roots.
RANDOM=$$
for i in 'seq 2'
do
echo "the first random number generated is:$RANDOM"
echo "the square root is :{$RANDOM^(1/2)}"
echo "the second random number generated is:$RANDOM"
echo "the square root is :{$RANDOM^(1/2)}"
SUM={$RANDOM^(1/2)} + {$RANDOM^(1/2)}
done
